In [3]:
import pandas as pd

# Dataframe
     - 2d dim

In [31]:
# create a data frame usingb dict
data = {"Name":["ahmed", "raza", "asim", "asad", "ali"],
            "Father name":["anwar","anwar", "abdul_rub", "abdul_rub", " "],
            "Class":["12th", "9th", "11th", "10th", "12th"],  
            "Roll_num":[1001, 1002, 1003, 1004, 1005],
            "marks":[88, 87, 67, 57,48],
            }

In [32]:
data

{'Name': ['ahmed', 'raza', 'asim', 'asad', 'ali'],
 'Father name': ['anwar', 'anwar', 'abdul_rub', 'abdul_rub', ' '],
 'Class': ['12th', '9th', '11th', '10th', '12th'],
 'Roll_num': [1001, 1002, 1003, 1004, 1005],
 'marks': [88, 87, 67, 57, 48]}

In [33]:
std_data = pd.DataFrame(data)

In [34]:
std_data

    Name Father name Class  Roll_num  marks
0  ahmed       anwar  12th      1001     88
1   raza       anwar   9th      1002     87
2   asim   abdul_rub  11th      1003     67
3   asad   abdul_rub  10th      1004     57
4    ali              12th      1005     48

In [24]:
std_data.size

25

In [12]:
emp  = pd.read_csv("employee.csv")

In [13]:
emp

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0

In [14]:
emp.shape

(18, 6)

In [15]:
emp.index

RangeIndex(start=0, stop=18, step=1)

In [16]:
emp.size

108

In [25]:
emp.head(5)

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0
1       2    1107     Officer         IT  30.0   80000.0
2       3    1203     Officer         HR  28.0       NaN
3       4    1005     Manager         HR  45.0  120000.0
4       5    2123  Office Boy   Accounts  27.0   45000.0

In [26]:
emp.sample(3)

   Serial  Emp_ID Designation Department   Age    Salary
3       4    1005     Manager         HR  45.0  120000.0
8       9    1234     Manager         IT  23.0       NaN
5       6    2451  Accountant        NaN  34.0  100000.0

In [27]:
emp.tail(5)

    Serial  Emp_ID Designation  Department   Age    Salary
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0

# working with columns

#### acessinga a single column

In [28]:
std_data

    Name Father_name Class  Roll_num  marks
0  ahmed       anwar  12th      1001     88
1   raza       anwar   9th      1002     87
2   asim   abdul_rub  11th      1003     67
3   asad   abdul_rub  10th      1004     57
4    ali              12th      1005     48

In [29]:
std_data["Name"]

0    ahmed
1     raza
2     asim
3     asad
4      ali
Name: Name, dtype: object

In [30]:
std_data.Name

0    ahmed
1     raza
2     asim
3     asad
4      ali
Name: Name, dtype: object

In [35]:
std_data["Father name"]

0        anwar
1        anwar
2    abdul_rub
3    abdul_rub
4
Name: Father name, dtype: object

In [ ]:
std_data.father name

In [36]:
emp.Department

0       Accounts
1             IT
2             HR
3             HR
4       Accounts
5            NaN
6       Accounts
7             IT
8             IT
9     Production
10    Production
11       Account
12    Production
13            IT
14            IT
15           NaN
16    Production
17      Accounts
Name: Department, dtype: object

In [37]:
emp["Department"]

0       Accounts
1             IT
2             HR
3             HR
4       Accounts
5            NaN
6       Accounts
7             IT
8             IT
9     Production
10    Production
11       Account
12    Production
13            IT
14            IT
15           NaN
16    Production
17      Accounts
Name: Department, dtype: object

#### acessing more then one column form a data

In [38]:
std_data["Name"]

0    ahmed
1     raza
2     asim
3     asad
4      ali
Name: Name, dtype: object

In [39]:
std_data[["Name", "Father name", "Class"]]

    Name Father name Class
0  ahmed       anwar  12th
1   raza       anwar   9th
2   asim   abdul_rub  11th
3   asad   abdul_rub  10th
4    ali              12th

In [40]:
emp[["Emp_ID", "Department", "Salary"]]

    Emp_ID  Department    Salary
0     1101    Accounts  200000.0
1     1107          IT   80000.0
2     1203          HR       NaN
3     1005          HR  120000.0
4     2123    Accounts   45000.0
5     2451         NaN  100000.0
6     1111    Accounts  110000.0
7     1001          IT   75000.0
8     1234          IT       NaN
9     2156  Production   89000.0
10    6543  Production  100000.0
11    3214     Account  123000.0
12    2156  Production   89000.0
13    1098          IT  100000.0
14    2912          IT   90000.0
15    1222         NaN       NaN
16    2156  Production   89000.0
17    2123    Accounts   45000.0

In [44]:
std_data["Grade"] = "A+"

In [45]:
std_data

    Name Father name Class  Roll_num  marks Grade
0  ahmed       anwar  12th      1001     88    A+
1   raza       anwar   9th      1002     87    A+
2   asim   abdul_rub  11th      1003     67    A+
3   asad   abdul_rub  10th      1004     57    A+
4    ali              12th      1005     48    A+

In [47]:
emp["Gender"] = "Male"

In [48]:
emp

    Serial  Emp_ID Designation  Department   Age    Salary Gender
0        1    1101     Manager    Accounts  50.0  200000.0   Male
1        2    1107     Officer          IT  30.0   80000.0   Male
2        3    1203     Officer          HR  28.0       NaN   Male
3        4    1005     Manager          HR  45.0  120000.0   Male
4        5    2123  Office Boy    Accounts  27.0   45000.0   Male
5        6    2451  Accountant         NaN  34.0  100000.0   Male
6        7    1111  Accountant    Accounts   NaN  110000.0   Male
7        8    1001     Officer          IT  25.0   75000.0   Male
8        9    1234     Manager          IT  23.0       NaN   Male
9       10    2156    Engineer  Production  45.0   89000.0   Male
10      11    6543     Officer  Production  29.0  100000.0   Male
11      12    3214  Accountant     Account  49.0  123000.0   Male
12      13    2156    Engineer  Production  45.0   89000.0   Male
13      14    1098     Officer          IT  25.0  100000.0   Male
14      15    2912     Officer          IT  31.0   90000.0   Male
15      16    1222     Officer         NaN  25.0       NaN   Male
16      17    2156    Engineer  Production  45.0   89000.0   Male
17      18    2123  Office Boy    Accounts  27.0   45000.0   Male

# we can add new columns using our data
    - broad casting
        - applying function/function apply
        - list comprihension
        - lambda function

# Applying function
    - Create and apply a custum function to transform or genrate new data from existing data

In [49]:
emp

    Serial  Emp_ID Designation  Department   Age    Salary Gender
0        1    1101     Manager    Accounts  50.0  200000.0   Male
1        2    1107     Officer          IT  30.0   80000.0   Male
2        3    1203     Officer          HR  28.0       NaN   Male
3        4    1005     Manager          HR  45.0  120000.0   Male
4        5    2123  Office Boy    Accounts  27.0   45000.0   Male
5        6    2451  Accountant         NaN  34.0  100000.0   Male
6        7    1111  Accountant    Accounts   NaN  110000.0   Male
7        8    1001     Officer          IT  25.0   75000.0   Male
8        9    1234     Manager          IT  23.0       NaN   Male
9       10    2156    Engineer  Production  45.0   89000.0   Male
10      11    6543     Officer  Production  29.0  100000.0   Male
11      12    3214  Accountant     Account  49.0  123000.0   Male
12      13    2156    Engineer  Production  45.0   89000.0   Male
13      14    1098     Officer          IT  25.0  100000.0   Male
14      15    2912     Officer          IT  31.0   90000.0   Male
15      16    1222     Officer         NaN  25.0       NaN   Male
16      17    2156    Engineer  Production  45.0   89000.0   Male
17      18    2123  Office Boy    Accounts  27.0   45000.0   Male

In [50]:
def cat_age(age):
    if age <25:
        return "young"
    elif age < 40:
        return "Middle"
    else:
        return "Senior"

In [51]:
emp["Age_cat"] = emp.Age.apply(cat_age)

In [52]:
emp

    Serial  Emp_ID Designation  Department   Age    Salary Gender Age_cat
0        1    1101     Manager    Accounts  50.0  200000.0   Male  Senior
1        2    1107     Officer          IT  30.0   80000.0   Male  Middle
2        3    1203     Officer          HR  28.0       NaN   Male  Middle
3        4    1005     Manager          HR  45.0  120000.0   Male  Senior
4        5    2123  Office Boy    Accounts  27.0   45000.0   Male  Middle
5        6    2451  Accountant         NaN  34.0  100000.0   Male  Middle
6        7    1111  Accountant    Accounts   NaN  110000.0   Male  Senior
7        8    1001     Officer          IT  25.0   75000.0   Male  Middle
8        9    1234     Manager          IT  23.0       NaN   Male   young
9       10    2156    Engineer  Production  45.0   89000.0   Male  Senior
10      11    6543     Officer  Production  29.0  100000.0   Male  Middle
11      12    3214  Accountant     Account  49.0  123000.0   Male  Senior
12      13    2156    Engineer  Production  45.0   89000.0   Male  Senior
13      14    1098     Officer          IT  25.0  100000.0   Male  Middle
14      15    2912     Officer          IT  31.0   90000.0   Male  Middle
15      16    1222     Officer         NaN  25.0       NaN   Male  Middle
16      17    2156    Engineer  Production  45.0   89000.0   Male  Senior
17      18    2123  Office Boy    Accounts  27.0   45000.0   Male  Middle

In [55]:
emp.Age.apply(cat_age)

0     Senior
1     Middle
2     Middle
3     Senior
4     Middle
5     Middle
6     Senior
7     Middle
8      young
9     Senior
10    Middle
11    Senior
12    Senior
13    Middle
14    Middle
15    Middle
16    Senior
17    Middle
Name: Age, dtype: object